config/routes.rb
Rails.application.routes.draw do
  resources :stcs
  resources :courses
  get 'sessions/new'

  get 'welcome/index'



  root 'welcome#index'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'users/:id', to: 'stcs#create'


  resources :users
 resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/stc.rb
class Stc < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/controllers/stcs_controller.rb
class StcsController < ApplicationController
  before_action :set_stc, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  # respond_to allows us to render to the same page using Ajax/jScript

  # GET /stcs
  # GET /stcs.json
  def index
    @stcs = Stc.all
  end

  # GET /stcs/1
  # GET /stcs/1.json
  def show
    @courses = Course.all
  end

  # GET /stcs/new
  def new
    @stc = Stc.new
  end

  # GET /stcs/1/edit
  def edit
  end

  # POST /stcs
  # POST /stcs.json
  def create
    @stc = Stc.new(stc_params)


      if @stc.save
        #format.html { redirect_to @stc, notice: 'Stc was successfully created.' }
        #format.json { render :show, status: :created, location: @stc }
         flash[:success] = "Course added "
         respond_to do |format|
           format.html
           format.json
         end
         

      else
        flash[:notice] = "Course addition failed"
       end
  end

  # PATCH/PUT /stcs/1
  # PATCH/PUT /stcs/1.json
  def update
    respond_to do |format|
      if @stc.update(stc_params)
        format.html { redirect_to @stc, notice: 'Stc was successfully updated.' }
        format.json { render :show, status: :ok, location: @stc }
      else
        format.html { render :edit }
        format.json { render json: @stc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stcs/1
  # DELETE /stcs/1.json
  def destroy
    @stc.destroy
    respond_to do |format|
      format.html { redirect_to stcs_url, notice: 'Stc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stc
      @stc = Stc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stc_params
      params.require(:stc).permit!
    end
    end

app/helpers/stcs_helper.rb
module StcsHelper
end

app/views/stcs/_form.html.erb
<%= form_for(Stc.new, action:'stcs#create',remote: true) do |form| %>

  <%= form.collection_select(:course_id, Course.all,:id, :title,{}, { :multiple => false}) %>
  <%= form.select(:semester, options_for_select([['--------','-----------'], ['Fall', 'Fall'], ['Spring', 'Spring'],['Summer', 'Summer']])) %>
  <%= form.select(:year, options_for_select([['--------','-----------'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017']])) %>
  <%= form.select(:user_id, options_for_select([[1,@user.id]])) %>
  <div class="actions">
    <%= form.submit %>
    <% end %>

  </div>

app/views/stcs/_show.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(Stc.new, url:{action:'new'}) do |f| %>
  <% @courses.find(1) do |course| %>
    <%= render 'shared/error_messages' %>
    <%= label_tag course.title, course.title %>
    <%= f.label :semester %>
<<<<<<< HEAD
    <%= select_tag(:semester, options_for_select([['--------','-----------'], ['Fall', 'Fall'], ['Spring', 'Spring']])) %>
    <%= select_tag(:year, options_for_select([['--------','-----------'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017']])) %>
      <%= f.submit "Student taken course", class: "btn btn-primary" %>

  <%end%>

=======
    <%= select_tag(:semester, options_for_select([['--------','-----------'], ['Fall', 'Fall'], ['Spring', 'Spring'],['Summer', 'Summer']])) %>
    <%= select_tag(:year, options_for_select([['--------','-----------'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017']])) %>
    <%end%>
>>>>>>> a5247b3296662d5831860db85bf0a1aaf0319c41

app/views/stcs/edit.html.erb
<h1>Editing Stc</h1>

<%= render 'form', stc: @stc %>

<%= link_to 'Show', @stc %> |
<%= link_to 'Back', stcs_path %>

app/views/stcs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stcs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stcs.each do |stc| %>
      <tr>
        <td><%= link_to 'Show', stc %></td>
        <td><%= link_to 'Edit', edit_stc_path(stc) %></td>
        <td><%= link_to 'Destroy', stc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stc', new_stc_path %>

app/views/stcs/new.html.erb
<h1>New Stc</h1>

<%= render 'form', stc: @stc %>

<%= link_to 'Back', stcs_path %>

app/views/stcs/new.js.erb
$('#class-form').html("<%= j (render 'stcs/form.html.erb' )")

app/views/stcs/show.html.erb
<p id="notice"><%= notice %></p>
<%= form_for(Stc.new, url:{action:'new'}) do |f| %>
  <% @courses.each do |course| %>
    <%= render 'shared/error_messages' %>
    <%= label_tag course.title, course.title %>
    <%= f.label :semester %>
    <%= select_tag(:semester, options_for_select([['--------','-----------'], ['Fall', 'Fall'], ['Spring', 'Spring']])) %>
    <%= select_tag(:semester, options_for_select([['--------','-----------'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017']])) %>
    <%end%>

  <%= f.submit "Student taken course", class: "btn btn-primary" %>
<% end %>